# Generated by Django 4.1.3 on 2022-11-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='kelas',
            field=models.CharField(default='A', max_length=30),
        ),
    ]
