# Generated by Django 4.1.3 on 2022-11-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mahasiswa', '0002_mahasiswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='nrp',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
